item = [
    ('tp_founder_eo', ['']), 
    ('tp_fullname_eo', ['']), 
    ('tp_shortname_eo', ['']), 
    ('tp_expert_advisory_org', ['НМС']), 
    ('tp_protocol_number', ['']), 
    ('tp_meeting_date_smc', ['']), 
    ('tp_date_approval_program', ['']), 
    ('tp_surname_head_eo', ['']), 
    ('tp_eo_lvl', ['']), 
    ('tp_program_name', ['']), 
    ('en_orientation', ['Художественная']), 
    ('tp_addressee_program', ['']), 
    ('tp_addressee_lvl', ['']), 
    ('tp_implementation_place', ['']), 
    ('tp_approval_year', ['2022']), 
    ('tp_surname_originator', ['']), 
    ('en_type_activity', ['Театр']), 
    ('en_relevance', ['']), 
    ('en_program_objectives ', ['']), 
    ('en_new_exp', ['']), 
    ('en_training_periodn', ['36']), 
    ('en_duration_lesson_choice', ['3']), 
    ('en_form_edu', ['очная']), 
    ('en_subject_taskss', ['Сформировать общее представление о театре', 'Научить практическим навыкам сценической речи и работы с художественным текстом']),
    ('en_metasubject_tasks_no', ['Научить основам кооперации']), 
    ('en_personal_tasks', ['']), 
    ('en_form_education', ['']), 
    ('cop_material_support_1', ['компьютер', 'проектор']), 
    ('cop_material_support_2', ['item1', 'item2']), 
    ('cop_technical_support_1', ['']), 
    ('cop_technical_support_2', ['']), 
    ('cop_form_visual', ['']), 
    ('cop_form_control', ['']), 
    ('cop_materials_edu', ['']), 
    ('cop_list_sourse_2', ['']), 
    ('cop_list_sourse_3', ['']), 
    ('cop_list_sourse_1', [''])
]